import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms and Conditions | WebGrab',
  description: 'Terms and Conditions for WebGrab - Modern Design & Digital Growth Agency',
};

export default function TermsAndConditions() {
  return (
    <div className="section" style={{ minHeight: '100vh', paddingTop: '150px' }}>
      <div className="container">
        <h1 className="heading-lg text-gradient" style={{ marginBottom: '2rem' }}>Terms and Conditions</h1>
        
        <div className="glass" style={{ padding: '3rem', borderRadius: '24px', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>1. Agreement to Terms</h2>
            <p className="text-body">
              These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and WebGrab ("we," "us," or "our"), concerning your access to and use of our website as well as our web design, development, and digital agency services.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>2. Digital Services</h2>
            <p className="text-body" style={{ marginBottom: '1rem' }}>
              WebGrab provides digital solutions including but not limited to:
            </p>
            <ul className="text-body" style={{ paddingLeft: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <li>Custom Web Design & UI/UX Services</li>
              <li>Full-Stack Web Development & Web Applications</li>
              <li>AI Business Automation Integrations</li>
              <li>Digital Growth & Marketing Strategies</li>
            </ul>
            <p className="text-body" style={{ marginTop: '1rem' }}>
              All projects are subject to separate service agreements or statements of work (SOW) which detail specific deliverables, timelines, and payment terms.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>3. Intellectual Property Rights</h2>
            <p className="text-body">
              Unless otherwise indicated or agreed upon in a specific project SOW, the website, source code, designs, and all other assets generated by WebGrab remain our intellectual property until full payment is received. Upon project completion and final payment, ownership rights transfer to the client as stipulated in the service agreement.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>4. Client Responsibilities</h2>
            <p className="text-body">
              Clients are expected to provide necessary materials, feedback, and approvals in a timely manner to ensure project timelines are met. Delays on the client's end may result in corresponding delays in delivery.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>5. Revisions and Maintenance</h2>
            <p className="text-body">
              Our web development and design projects typically include a defined number of revision rounds. Any additional changes requested beyond the agreed scope will be billed at our standard hourly rate. Ongoing maintenance, hosting, or updates require a separate maintenance contract.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>6. Limitation of Liability</h2>
            <p className="text-body">
              WebGrab shall not be liable for any indirect, consequential, or special damages arising out of or in connection with the use of our services or website. We do not guarantee uninterrupted functionality of digital products post-launch unless covered under a specific maintenance agreement.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>7. Modifications</h2>
            <p className="text-body">
              We reserve the right to change, modify, or remove the contents of our website and update these Terms at any time without prior notice. Continued use of our services implies acceptance of the revised Terms.
            </p>
          </div>

          <div>
            <h2 className="heading-md" style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', marginBottom: '1rem', color: 'var(--foreground)' }}>8. Contact Us</h2>
            <p className="text-body">
              For any questions regarding these Terms and Conditions or our service agreements, please contact us at legal@webgrab.com.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
